---
title: "Rshiny Dashboard"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(plotly)
library(survey)
library(MEPS)
library(shiny)
fyc23  <- read_MEPS(file = "h251")
cond23 <- read_MEPS(file = "h249")
```

```{r, include=FALSE}

## -------------------------------------------------------------
## 1. Load raw MEPS FY 2023 data
## -------------------------------------------------------------

fyc23  <- read_MEPS(file = "h251")
cond23 <- read_MEPS(file = "h249")

names(fyc23)  <- tolower(names(fyc23))
names(cond23) <- tolower(names(cond23))

## -------------------------------------------------------------
## 2. Clean person-level file fyc23
## -------------------------------------------------------------

fyc23_clean <- fyc23

# Keep only people with positive weights
fyc23_clean <- fyc23_clean[fyc23_clean$perwt23f > 0, ]

# Convert special missing codes to NA for numeric variables
num_vars <- sapply(fyc23_clean, is.numeric)
for (j in which(num_vars)) {
  x <- fyc23_clean[[j]]
  x[x %in% c(-1, -7, -8, -9, -15)] <- NA
  fyc23_clean[[j]] <- x
}

# Select variables we need now + variables we will create later
keep_vars <- c(
  "dupersid", "panel", "varstr", "varpsu", "perwt23f",
  "totexp23",               # spending
  "agelast", "sex", "racethx",
  "povcat23", "inscov23"
)

fyc23_clean <- fyc23_clean[, keep_vars]


## -------------------------------------------------------------
## 3. Create demographic variables
## -------------------------------------------------------------

### 3.1 Age groups
fyc23_clean$age_cat4 <- cut(
  fyc23_clean$agelast,
  breaks = c(-Inf, 17, 44, 64, Inf),
  labels = c("0-17", "18-44", "45-64", "65+")
)

### 3.2 Sex
fyc23_clean$sex_f <- factor(
  ifelse(fyc23_clean$sex == 1, "Male", "Female"),
  levels = c("Male", "Female")
)

### 3.3 Race/ethnicity
fyc23_clean$race4 <- NA
fyc23_clean$race4[fyc23_clean$racethx == 1] <- "Hispanic"
fyc23_clean$race4[fyc23_clean$racethx == 2] <- "NH White"
fyc23_clean$race4[fyc23_clean$racethx == 3] <- "NH Black"
fyc23_clean$race4[fyc23_clean$racethx %in% c(4, 5)] <- "NH Asian/Other"

fyc23_clean$race4 <- factor(
  fyc23_clean$race4,
  levels = c("NH White", "NH Black", "Hispanic", "NH Asian/Other")
)

### 3.4 Poverty category
pov_labels <- c(
  "Poor", "Near-poor", "Low income",
  "Middle income", "High income"
)

fyc23_clean$povcat_f <- factor(
  fyc23_clean$povcat23,
  levels = 1:5,
  labels = pov_labels
)

### 3.5 Insurance coverage
ins_labels <- c("Any private", "Public only", "Uninsured")

fyc23_clean$inscov_f <- factor(
  fyc23_clean$inscov23,
  levels = 1:3,
  labels = ins_labels
)

```

-----------------------------------------------------------------------

```{r, echo=FALSE}
age_group <- fyc23_clean |> distinct(age_cat4) |> pull()

selectInput(
  inputId = "age_choice",
  label = h2("Select an age group"),
  choices = age_group,
  selected = "65+"
)

```


-----------------------------------------------------------------------

### Total Expenditure Among People in Different Age Groups

```{r, echo=FALSE}
renderPlotly({
  fyc23_clean |>
    filter(age_cat4 == input[["age_choice"]]) |>
    plot_ly(
      x = ~age_cat4,
      y = ~totexp23,
      color = ~race4,
      type = "violin",
      mode = "markers"
    )|>
layout(
  xaxis = list(title = "Age Group"),
  yaxis = list(title = "Total Expenditures (USD) in 2023")
) 
})
```

-----------------------------------------------------------------------

### Chart B Household Income Distribution Among People in Different Insurance Groups
```{r, echo=FALSE}
insur_group <- fyc23_clean |> distinct(inscov_f) |> pull()

selectInput(
  inputId = "insurance_choice",
  label = h3("Choose an insurance type"),
  choices = insur_group,
  selected = "Uninsured"
)
```

```{r, echo=FALSE}
renderPlotly({
  fyc23_clean |>
    filter(inscov_f == input$insurance_choice) |>
    count(povcat_f) |>
    mutate(povcat_f = fct_reorder(povcat_f, n)) |>
    plot_ly(
      x = ~povcat_f,
      y = ~n,
      type = "bar"
    )|>
layout(
  xaxis = list(title = "Household Income Level"),
  yaxis = list(title = "Number of People")
)
})
```

### Chart C Total Expenditure among Male and Female

```{r, echo=FALSE}

sex_group <- fyc23_clean |> distinct(sex_f) |> pull()

selectInput(
  inputId = "sex_choice",
  label = h3("Choose a sex"),
  choices = sex_group,
  selected = "Male"
)

```


```{r, echo=FALSE}
renderPlotly({
  fyc23_clean |>
    filter(sex_f == input[["sex_choice"]]) |>
    plot_ly(
      x = ~inscov_f,
      y = ~totexp23,
      color = ~race4,
      type = "scatter",
      mode = "markers"
    )|>
layout(
  xaxis = list(title = "Insurance type"),
  yaxis = list(title = "Total Expenditures (USD) in 2023")
) 
})
```



